[data]
hospitals_data = "https://raw.githubusercontent.com/Freemanlabs/hospital-system-chatbot/master/data/hospitals.csv"
payers_data = "https://raw.githubusercontent.com/Freemanlabs/hospital-system-chatbot/master/data/payers.csv"
physicians_data = "https://raw.githubusercontent.com/Freemanlabs/hospital-system-chatbot/master/data/physicians.csv"
patients_data = "https://raw.githubusercontent.com/Freemanlabs/hospital-system-chatbot/master/data/patients.csv"
visits_data = "https://raw.githubusercontent.com/Freemanlabs/hospital-system-chatbot/master/data/visits.csv"
reviews_data = "https://raw.githubusercontent.com/Freemanlabs/hospital-system-chatbot/master/data/reviews.csv"

[model]
agent_model = "command-r-plus"
cypher_model = "command-r-plus"
qa_model = "command-r-plus"
